project:
  type: website
  output-dir: docs

website:
  title: "Stat515 Website"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - Project1.qmd
      - Project2.qmd

format:
  html:
    theme:
      - superhero
      - brand
    css: styles.css
    toc: true

editor: visual

